logo_title: TAO

style: black

favicon: /favicon.ico

menu:
  作品: /project
  #域名: /domain
  #友联: /links
  关于: /about
  Github: https://github.com/taotao7

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: wqFdrF3J2C3lJWUKyvcUbPoJ-gzGzoHsz
  appKey: o6gwanqWaUrXN7mliDcGHn0T

highlight:
  enable: true
